# Generated by Django 5.0.2 on 2024-02-11 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=300)),
                ('instructions', models.TextField()),
                ('api', models.CharField(max_length=300)),
            ],
        ),
    ]
